# Crash course on Python
Python is a general purpose programming language and one of the most popular
programming languages. It is widely used in the scientific community because
of its ease of use and simple syntax. Python also offers a large collection of
libraries that help to solve complex problems easily and build strong system
and data application.

[PEP8](https://realpython.com/python-pep8/) is one of the standards that
specifies guidelines and best practices on how to write Python code

This week is introductory week where we are learning the foundations of machine learning and developing an understanding of what it means for a machine to learn from data. Therefore, we are not going to train any machine learning models yet. 

The aim of this activity is to help you refresh your knowledge of Python Variables and Datatypes, Operators (Arithmetic, Logical, Comparison, Assignment, Membership, Conditional Statements, Iteration (for and while loops), Functions, Objects and Classes, and important Python Libraries for ML (Numpy, Matplotlib, Seaborn, Pandas, and Scikit-Learn.

You are required to do three things:
1. Carefully review the code in each cell and execute it to see the output. 
2. Read reference material(s) where provided.
3. Complete small tasks to help you practice the learned concepts.

---
## Variables and Datatypes
Python has different data types, here is the most common ones

| Data Types   | Examples            | Explanation          | Mutable? |
| ------------ | ------------------- | -------------------- | -------- |
| Strings      | "Hi!", '1.3'        | Text                 | No       |
| Integers     | 49                  | Whole numbers        | No       |
| Floats       | 3.14                | Decimal Numbers      | No       |
| Booleans     | True, False         | Truth values         | No       |
| Lists        | \[1, 'a', [1.5, 2]\]| A collection of data | Yes      |
| Tuples       | (1, 2, 3, 4, 5)     | A collection of data | Yes      |
| Dictionaries | {"a": 1, "b": True} | A collection of data | Yes      |

In [1]:
# Assigning data to variables
# NOTE: variable names should be descriptive
var_greeting = "Hello World"
var_int = 254
var_float = 25.43
var_names = ["Anna", "Bella", "Cora"]
var_grade_dict = {'Course': 'ML', 'Grade': 'A'} # key: value

# You can access List elements with their index
# and access Dict elements with their key
print('Student:', var_names[0], 'got', var_grade_dict['Grade'])

# When in doubt you can always check data types
print('Variables data types')
print('var_greeting', type(var_greeting))
print('var_int', type(var_int))
print('var_float', type(var_float))
print('var_names', type(var_names))
print('var_grade_dict', type(var_grade_dict))

Student: Anna got A
Variables data types
var_greeting <class 'str'>
var_int <class 'int'>
var_float <class 'float'>
var_names <class 'list'>
var_grade_dict <class 'dict'>


Using list and tuple

In [2]:
x = [1, 2, 3]  # creating a list
y = x  # assigning a reference
y[0] += 1
# The change is in both x and y because both point to the same object
print(x, y)

[2, 2, 3] [2, 2, 3]


In [3]:
x = (1, 2, 3)  # creating a tuple
y = x
# y[0] += 1 gives error because it's immutable
y += (4, 5)  # a new tuple is generated to
print(x, y)

(1, 2, 3) (1, 2, 3, 4, 5)


In [4]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('x size:', len(x))
print('The second element in x:', x[1])
print('The last element in x:', x[-1])
print('The first 3 elements in x:', x[:3])  # also x[0: 3] works

x size: 10
The second element in x: 2
The last element in x: 10
The first 3 elements in x: [1, 2, 3]


### Task 1:
Print the last 3 elements of the list x

In [5]:
# Solve here
print(f"{x[-3:]}")

[8, 9, 10]


In [ ]:
%%sql


## Operators
[Reference](https://www.geeksforgeeks.org/python-operators/)

When dealing with data, knowing python operators and how they work can make
your code smaller and more efficient.

We will look at the operator that might be new to you.
Refer to this [reference](https://www.geeksforgeeks.org/python-operators/)
for all the operations.

| Operator | Description                                                    | Syntax        |
| -------- |----------------------------------------------------------------|---------------|
| //       | Division (floor): divides the first operand by the second      | x//y          |
| **       | Power: Returns first raised to power second                    | x**y          |
| is       | True if the operands are identical (they share a memory space) | x is y        |
| is not   | True if the operands are not identical                         | x is not y    |
| in       | True if value is found in the sequence                         | x in y        |
| not in   | True if value is not found in the sequence                     | x not in y    |
| Ternary  | testing a condition in a single line                           | x if a else y |

In [6]:
# //	Division (floor): divides and floor the output
a = 10
b = 3
div = a / b
div_floor = a // b
div_remainder = a % b # aka "a modulo b" or "a mod b"

print(f"{div=}, {div_floor=}, {div_remainder=}")

div=3.3333333333333335, div_floor=3, div_remainder=1


In [7]:
# negative division could be counter-intuitive
print (5//2)
print (-5//2) # floor(-2.333) gives the integer smaller -> -3


2
-3


In [8]:
# Power
pwr = a ** b
print(pwr)

1000


In [9]:
# is, is not
# NOTE:
# `==` is the equality operator
# `is` is the identity operator
# - Use **`==`** when you want to check if two objects have equal **values**.
# - Use **`is`** when you want to check if two objects refer to the same memory location.

### Special Notes:
# - For **immutable objects** like integers and strings, `is` may sometimes seem to behave like `==` because the Python interpreter often optimizes memory usage by reusing objects for small integers and interned strings.

c = a
print(a is not b)
print(a is c)

True
True


In [10]:
# in, not in
x, y = 24, 20
l = [10, 20, 30, 40, 50]

print(x not in l)
print(y in l)


True
True


In [11]:
# Ternary operator
if a < b:
    print(a)
else:
    print(b)

# [on_true] if [expression] else [on_false]
minimum = a if a < b else b
print(minimum)

3
3


## Iteration
The 2 main loops in python are `while` and `for` loops

[Reference](https://www.geeksforgeeks.org/loops-in-python/)

In [12]:
# While loop
count = 0
while count < 3:
    count = count + 1
    print("count = ", count)

count =  1
count =  2
count =  3


In [13]:
# Combining else with while to execute something after the loop
# NOTE: if the while loop ends with a `break` command, the `else` block will NOT execute. That's the reason you would use the else block and not just put a command after the while block.
count = 0
while count < 3:
    count = count + 1
    print("count = ", count)
else:
    print("In the else. count = ", count)

count =  1
count =  2
count =  3
In the else. count =  3


[`range()`](https://docs.python.org/3/library/functions.html#func-range) is
a built-in generator function that is used to generate numbers in a given range.

It takes up to 3 parameter `start`, `stop`, `step`.
If not given,`start` defaults to `0`, and `step` to `1`.

Examples:
- `range(0, 10, 1)` -> `[0, 1, 2, ..., 9]`. note that `stop` isn't included.
- `range(0, 10, 2)` -> `[0, 2, 4, 6, 8]`. even numbers.
- `range(0, 10)` -> Only `start` and `stop`. same as `range(0, 10, 1)`.
- `range(10)` -> Only `stop`. same as `range(0, 10, 1)`.
- `range(10, 0, -1)` -> `[10, 9, 8, ..., 1]`.

In [14]:
# range for loop
my_list = [10, 20, 30, 40]
print('looping over list elements by index using "range()"')
for i in range(0, len(my_list)):
    print(my_list[i])

print('looping over list elements using "in"')
for element in my_list:
    print(element)

looping over list elements by index using "range()"
10
20
30
40
looping over list elements using "in"
10
20
30
40


In [15]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80]
print('looping over list elements by index using "range()"')
for i in range(0, len(my_list)):
    if i == 5:  # break the loop after 5 iterations
        break
    elif i%2 == 1:  # skipping odd indices
        continue
    print(my_list[i])

looping over list elements by index using "range()"
10
30
50


### Task 2:
Make a list that have all the integers from 0 to 99 that are divisible by 4 but
not divisible by 6.

Hint: `my_list.append(a)` adds `a` to the end of the `my_list`.

In [16]:
# Solve here
my_list_2 = [x for x in range(100) if x % 4 == 0 and x % 6 != 0]
# NOTE: list comprehensions are generally faster than appending in a loop.
# If you're just initializing a list, prefer list comprehensions.
print(f"{my_list_2=}")

# check the solution:
for number in my_list_2:
    assert number % 4 == 0
    assert number % 6 != 0
    print(f"{number} is ok")

my_list_2=[4, 8, 16, 20, 28, 32, 40, 44, 52, 56, 64, 68, 76, 80, 88, 92]
4 is ok
8 is ok
16 is ok
20 is ok
28 is ok
32 is ok
40 is ok
44 is ok
52 is ok
56 is ok
64 is ok
68 is ok
76 is ok
80 is ok
88 is ok
92 is ok


## Functions
Functions is very useful to use a block of code multiple times.

In [17]:
def my_function_name():
    print('Hi from a function')

my_function_name()
my_function_name()

Hi from a function
Hi from a function


In [18]:
def double(x):
    return x * 2

print(double(3))

6


## Classes
Python is an Object Oriented Programming (OOP) langauge. Here are how classes are used

[geeksforgeeks.org/python-classes-and-objects](https://www.geeksforgeeks.org/python-classes-and-objects/)

In [19]:
class Dog:

    # A simple class
    # attribute
    attr1 = "mammal"
    attr2 = "dog"

    # A sample method
    def self_identify(self):
        print("I'm a", self.attr1)
        print("I'm a", self.attr2)

# Object instantiation
Rodger = Dog()

# Accessing class attributes
# and method through objects
print(Rodger.attr1)
Rodger.self_identify()

mammal
I'm a mammal
I'm a dog


---
## Install external modules
Python community offers a huge variety of modules to eliminate the need for
writing codes from scratch.
[pip](https://pypi.org/project/pip/) is a package installer for Python. You
can use pip to install packages from the Python Package Index and other indexes.

To install a package you can run this command in your terminal:
- Unix/macOS: `python3 -m pip install <package name>` or `pip3 install <package name>`
- Windows: `py -m pip install <package name>` or `pip install <package name>`

[Further reading](https://pip.pypa.io/en/stable/cli/pip_install/)
on pip usage and how to write and install requirements files.

You can also run terminal command from your jupyter notebook using
[magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html)

To do so, you put `!` before your command so that jupyter understand executing
it in the terminal.

In [23]:
# avoid install warning
import importlib.util
if importlib.util.find_spec("numpy") is None:
    # https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-sx
    !pip install numpy

---
## Numpy
While python is a powerful, it is very slow compared to C/C++ since it's and
interpreted language with dynamic typing. Numpy is python library that is
implemented in C/C++. giving us the ease of development of python with the
performance of C. depending on the operation numpy could be up to 100x faster.
Moreover, it has various functions to perform linear algebra and array operations.

[numpy.org absolute beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

In [24]:
import numpy as np

In [26]:
my_np_list = np.random.randint(low=-100, high=100, size=20)
print(my_np_list)

[ 70  37  74 -11 -33  -6 -98  -6 -63 -87 -57  48  80  88 -65 -97 -89  71
  38  42]


Here is some of the most common used function

In [27]:
print('shape:', my_np_list.shape)
print('sum:', my_np_list.sum())
print('min:', my_np_list.min())
print('max:', my_np_list.max())
print('abs:', np.abs(my_np_list))
my_np_list.sort()
print('after .sort():', my_np_list)
print('doubling the array', my_np_list * 2) # broadcasting

shape: (20,)
sum: -64
min: -98
max: 88
abs: [70 37 74 11 33  6 98  6 63 87 57 48 80 88 65 97 89 71 38 42]
after .sort(): [-98 -97 -89 -87 -65 -63 -57 -33 -11  -6  -6  37  38  42  48  70  71  74
  80  88]
doubling the array [-196 -194 -178 -174 -130 -126 -114  -66  -22  -12  -12   74   76   84
   96  140  142  148  160  176]


### Task 3:
Print the mean, variance and standard deviation of `my_np_list`

In [29]:
# Solve here
print(f"{my_np_list=}")
print(f"{my_np_list.mean()=}")
print(f"{my_np_list.var()=}")
print(f"{my_np_list.std()=}")

my_np_list=array([-98, -97, -89, -87, -65, -63, -57, -33, -11,  -6,  -6,  37,  38,
        42,  48,  70,  71,  74,  80,  88])
my_np_list.mean()=np.float64(-3.2)
my_np_list.var()=np.float64(4173.26)
my_np_list.std()=np.float64(64.60077398917137)


In [33]:
# 2D arrays
x = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
    ],
    np.int32,
)
print(x)
print(f'{x.shape = }')
print('accessing element:', x[1, 2])
print('slice of an array:', x[0:2, 0:3])
print('row:', x[0, :])
print('column:', x[:, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x.shape = (3, 4)
accessing element: 7
slice of an array: [[1 2 3]
 [5 6 7]]
row: [1 2 3 4]
column: [ 4  8 12]


In [34]:
# speed
from time import time

start_time = time()
my_list = [1] * 10000000
sum(my_list)
list_time = time() - start_time

start_time = time()
my_np_list = np.ones(10000000)
my_np_list.sum()
np_time = time() - start_time

print('numpy is', list_time/np_time, ' times faster than list')

numpy is 1.675840215804741  times faster than list


### Task 4
Install the following packages: `matplotlib`, `pandas`, `seaborn` and `sklearn`

In [ ]:
# Solve here
# NOTE: using uv as a package manager. uv add ... has already been used.
# NOTE: sklearn is deprecated. Used scikit-learn


---
## Matplotlib
Matplotlib is a comprehensive library for creating static, animated, and
interactive visualizations in Python.

[Reference](https://matplotlib.org/stable/tutorials/introductory/pyplot.html#sphx-glr-tutorials-introductory-pyplot-py)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline # to plot in side the notebook

In [ ]:
# Line plot
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='Hours studied (s)', ylabel='voltage (mV)',
       title='Change in volt over time')
ax.grid()
plt.show() # Show the plot

In [ ]:
# different plots for categorical data
names = ['group_a', 'group_b', 'group_c']
values = [1, 10, 100]

plt.figure(figsize=(9, 5))

plt.subplot(131)  # To creat 1 by 3 grid and plot in the 1st subplot
plt.bar(names, values)
plt.subplot(132)  # plot in the 2nd subplot
plt.scatter(names, values)
plt.subplot(133)  # plot in the 3nd subplot
plt.plot(names, values)
plt.suptitle('Categorical Plotting')
plt.show()

---
## Pandas
[Pandas](https://pandas.pydata.org/docs/) is a fast, powerful, flexible and
easy to use open source data analysis and manipulation tool.


In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv('petrol_consumption.csv')
df.info()

In [ ]:
df.head(5)

In [ ]:
df.describe()


In [ ]:
# access a columns
print(df['Petrol_tax'].head())
print(df[['Average_income', 'Paved_Highways']].head())

In [ ]:
# access a rows
df.iloc[[1, 2, 4]]

In [ ]:
# dropping a column
new_df = df.drop(['Average_income', 'Paved_Highways'], axis=1)
new_df.head()

In [ ]:
# Drop a row by index
new_df = df.drop([0, 1])
new_df.head()

In [ ]:
# pandas support many operations similar to numpy
print('Sum of columns\n', df.sum(), '\n')
print('Sum of all the data frame\n', df.sum().sum(), '\n')
print('Mean of columns\n', df.mean(), '\n')
print('Converting dataframe to numpy array\n', type(df.to_numpy()))

---
## Seaborn
Seaborn is a Python data visualization library based on matplotlib. It provides
a high-level interface for drawing attractive and informative statistical graphics.
Usually used with pandas.

[Reference](https://seaborn.pydata.org/examples/index.html)
[Examples](https://www.geeksforgeeks.org/python-seaborn-tutorial/)

In [ ]:
import seaborn as sns

df = sns.load_dataset('tips')

graph = sns.FacetGrid(df, col ="sex",  hue ="day")
graph.map(plt.scatter, "total_bill", "tip", edgecolor ="w").add_legend()

plt.show()

---
## SKLearn

[SKLearn](https://scikit-learn.org/stable/modules/classes.html) is a simple
and efficient tools for predictive data analysis.
We will use it for classification, regression and clustering algorithms.

Usually datasets have two parts, data(or features) and targets(or labels).
We train our machine learning model to predict the target of a sample given
its features.

In [ ]:
# sklearn has some datasets inside it to learn and test on them
from sklearn import datasets
iris = datasets.load_iris()
print(f'Dataset shape: {iris.data.shape = }, {iris.target.shape = }')
print(f'Example of a sample: features: {iris.data[0]}, classification: {iris.target[0]}')

SKLearn gives a simple API to build models. Mainly it consists of two steps:
- Model creation: where we choose the model and set its parameters
- Fitting the data: Where we give our model the training data to learn from
- Prediction: where we can predict the label of a sample

`svm` is a prediction model(we will study how it works later in the course).

Here is an example on how to use an SKLearn model:

In [ ]:
from sklearn import svm
# setting the parameters needed by the algorithm
clf = svm.SVC(gamma=0.001, C=100.)
# Training on all the data except the last one
clf.fit(iris.data[:-1], iris.target[:-1])
# predicting the last sample
print('Our prediction', clf.predict(iris.data[-1:]), 'True value:', iris.target[-1:])